### PR TITLE
Fix pom description typos

### PR DESCRIPTION
**Pull request by andresaraujo**
Fixes typos in publish file

### CODE REVIEW

**Comment by Antag99** [comment]
Wait a sec. It's still mini*m*al, not mini*n*al.

**Comment by Antag99** [comment]
And the framework is called ash*le*y, not ash*el*y.

**Comment by Antag99** [comment]
The developer ID of @saltares should perhaps be changed from "siondream" to "saltares", but I'm not sure about that.

**Comment by saltares** [comment]
It should. @andresaraujo could you please fix the typos and squash everything into a single commit?

**Comment by andresaraujo** [comment]
Remind me never do a PR after midnight! I think everything should be okay now

**Comment by saltares** [comment]
Hehe, thanks!

**Pull request merged**
