### PR TITLE
Added a configurations map to the engine

### PR DESCRIPTION
**Pull request by Taivaan**
Very often I find that I need to share data across multiple systems, such as a SpriteBatch, an asset manager, a serialization component or the Box2D World, so I created a map in the engine to store these "configuration" items. This also allows systems to autoconfigure themselves by retrieving the data when added to the engine. It also allows systems to keep track of changes in configurations with the use of signals and listeners. If you like the idea, feel free to accept this pull request.

### CODE REVIEW

**Comment by laubed** [comment]
I wouldn't call it configuration items and instead call it UserObjects or CustomObjects becuase the system is so wide-scoped that users probably won't use it for configuration items only.

Otherwise i only see a problem because it's out of scope of ashley. It's indeed a usefull and handy system to have but not entity engine related in general.

**Comment by Taivaan** [comment]
Yes, it could potentially be used to store any object, the same way a system could potentially be used to store data or entities and components could store logic, but it's not its intended purpose, and that's why I call them configurations. I use this mainly to keep systems decoupled and stateless, e.g.: my collision system doesn't need to access the physics system to retrieve the Box2DWorld, it retrieves it from the configurations map. Another example: multiple rendering systems don't need to access one of the systems spritebatch, camera and viewport (or have each its own, or having to creating an entity, a component and a listener just for that system), they get them from the configurations map, making them independent and stateless (which also helps with serialization).

**Comment by mgsx-dev** [comment]
IMO keeping systems decoupled is a good practice but why not simply pass these shared object to system constructors. It works very well. I named them "context", for example "Box2DContext" owning the box2D world is first created and passed to my box2D related systems constructors : Box2DWorldSystem and Box2DDebugRenderSystem.

I don't know why you want to keep systems stateless, you're solution move the problem to the engine which would make it state-full. Why not serialize systems ? In my example, I serialize box2D world settings (time step, velocity iterations ...) owned by my Box2DWorldSystem.

Sorry but I don't see the benefits of your solution, maybe i missed something ?

**Comment by Taivaan** [comment]
Ok. Imagine I develop a game editor with ashley, and I want to allow developers to create systems and plug them automatically on ashley. One developer creates a physics system with Box2D, another wants to add a system that moves platforms from box2D, and other developer wants to create a plugin that makes the characters stick to the ground. They need the same box2DWorld object to add a listener, and they can't pass the box2DWorld to their constructors, because the engine can't possibly know what developers are going to need on their systems and provide the right arguments for the constructors. 

 That's why I added a place to store configurations on ashley, because whenever a configurable system is added to the engine it accesses the configurations, retrieves what it needs (or creates it if there's not a configuration yet) and voilà! It's autoconfigured and sharing the configuration data with other systems, without having to know anything about the other systems. And not only that, now that I have all the configurations on the same place, I can make a nice GUI that accesses that allows the user to modify the configurations stored there (e.g. changing the world iterations, gravity, etc) without much effort.

 And yes, I could make a wrapper for ashley and store the configurations on it instead of storing them on ashley, but the systems would have to know about this wrapper and be added to the engine through it, creating an unnecesary layer of complexity. Besides, the use of shared objects between systems is so common that I think it makes a lot of sense to put it directly on ashley.

About serialization, I think it's not a very good idea to serialize the system itself. If you change the system and try to deserialize the old version of the system, it might throw some exceptions. It's much less likely to happen if you load the new system and deserialize just the configuration. Same happens in the opposit case: If a configuration changes, you would only have to change the way in which you deserialize it, instad of having to change the deserialization of all the different systems that have access to that configuration.

And about the statefulness of Ashley: it's already stateful. It holds entities and systems

**Comment by mgsx-dev** [comment]
Your idea is not bad but it is a design choice for your editor and respond to your workflow constraints. 

There are so many ways to share object across systems (without modifying Ashley) depending of use of Ashley and I don't think there is a general solution.

**Comment by Taivaan** [comment]
It's not just for the editor, pretty much every game will have systems sharing data, and this provides a simple way to do this, allowing them to share configuration data, listen to changes in configurations and autoconfigure themselves when added to the engine, asides from being kept stateless.

**Comment by Lusito** [comment]
I like the idea of a lookup, but I don't think it should clutter the engine.

How about making it a separate class, like this:
```

public class Lookup implements Iterable<ObjectMap.Entry<Class, Object>> {
    private final static ObjectMap<Engine, Lookup> LOOKUPS = new ObjectMap();

    private final Engine engine;
    private final ObjectMap<Class, Object> lookup = new ObjectMap();
    public final Signal<Object> itemAdded = new Signal();
    public final Signal<Object> itemRemoved = new Signal();

    private Lookup(Engine engine) {
        this.engine = engine;
    }

    public static Lookup getFor(Engine engine) {
        Lookup lookup = LOOKUPS.get(engine);
        if (lookup == null) {
            lookup = new Lookup(engine);
            LOOKUPS.put(engine, lookup);
        }
        return lookup;
    }

    public static void freeFor(Engine engine) {
        Lookup lookup = LOOKUPS.get(engine);
        if (lookup != null) {
            lookup.clear();
            LOOKUPS.remove(engine);
        }
    }

    public Engine getEngine() {
        return engine;
    }

    @Override
    public Entries<Class, Object> iterator() {
        return lookup.entries();
    }

    public Object[] getAll() {
        Object[] configs = new Object[lookup.size];
        Values values = lookup.values();
        for (int i = 0; values.hasNext(); i++) {
            configs[i] = values.next();
        }
        return configs;
    }

    public <T> T get(Class<T> clazz) {
        return (T) lookup.get(clazz);
    }

    public <T> T put(Class<T> clazz, T item) {
        T old = (T) lookup.put(clazz, item);
        if(old != null) {
            notifyItemRemoved(old);
        }
        if (item instanceof LookupItem) {
            ((LookupItem) item).addedToLookup(this);
        }
        itemAdded.dispatch(item);
        return old;
    }

    public Object remove(Class<? extends Object> clazz) {
        Object item = lookup.remove(clazz);
        if (item != null) {
            notifyItemRemoved(item);
        }
        return item;
    }

    public Class remove(Object item) {
        Class type = lookup.findKey(item, true);
        if (type != null) {
            remove(type);
        }
        return type;
    }

    private void notifyItemRemoved(Object item) {
        if (item instanceof LookupItem) {
            ((LookupItem) item).removedFromLookup(this);
        }
        itemRemoved.dispatch(item);
    }

    public void clear() {
        for (Object value : lookup.values()) {
            notifyItemRemoved(value);
        }
        lookup.clear();
    }
}

public interface LookupItem {
    void addedToLookup(Lookup lookup);
    void removedFromLookup(Lookup lookup);
}

```

You could then use it like this:

```
Lookup lookup = Lookup.getFor(engine);
SpriteBatch batch = lookup.get(SpriteBatch.class);
```

(untested code)

**Comment by Taivaan** [comment]
You're right @Lusito, this definitely should be another class. I've been thinking about it for a while and found some more things that could be improved, so I'll probably create a whole new lookup module.

**Pull request closed without merging**
