### PR TITLE
fix remove out of bounds component from entity, fix libgdx/ashley#252

### PR DESCRIPTION
**Pull request by mgsx-dev**

### CODE REVIEW

**Comment by saltares** [comment]
Awesome thanks!

Is there a way to create the classes using reflection so that we don't have all those 64 classes definitions there?

**Comment by mgsx-dev** [comment]
I thought it couldn't be possible, I tried with Dynamic Proxy without success but I finally manage it with byte code.

**Comment by saltares** [comment]
Cool, looks good to me. Do you mind squashing the commits into 1?

Thanks!

**Comment by mgsx-dev** [comment]
No problem.

**Pull request merged**
