### PR TITLE
Entity#addAndReturn(Component) and Entity#remove(Class) generified

### PR DESCRIPTION
**Pull request by JensPiegsa**
* `addAndReturn` should not require an additional cast to the concrete component class

### CODE REVIEW

**Comment by JensPiegsa** [comment]
I wasn't able to build ashley and run the unit tests as I got this exception from IntelliJ:
`Could not determine the class-path for interface org.jetbrains.kotlin.kapt.idea.KaptGradleModel.`
I think the suggested change shouldn't break anything.

**Comment by mgsx-dev** [comment]
you can run tests outside of your IDE with gradle : `./gradlew test`

**Comment by Jkly** [comment]
Is it worth also changing `Entity#remove(Component)` so that it is also generified for parity?

**Comment by JensPiegsa** [comment]
@mgsx-dev Thanks, now locally all test are green, too.

@Jkly I think so. :-)

**Comment by dsaltares** [comment]
Sorry for having taken so long but I am not very active maintaining this project. Could you please resolve conflicts? Thanks.

**Pull request merged**
